version: "3.3"

services:
  web:
    hostname: web
    ports:
      - 3000:3000
      - 9229:9229
      - 5555:5555
    build: .
    volumes:
      - .:/server
    command: 
      - "npm"
      - "run"
      - "dev"

  db:
    env_file:
      - db.env
    image: postgres
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - /db/graphql-crud/data:/var/lib/postgresql