version: "3.3"

services:
  web:
    ports:
      - 3000:3000
      - 9229:9229
    build: .
    links:
      - graphql
    volumes:
      - .:/server
    command: 
      - "npm"
      - "run"
      - "dev"

  graphql:
    env_file:
      - hasura.env
    image: hasura/graphql-engine
    container_name: graphql-graphql
    ports:
      - 8080:8080
